options:
    nagios_context:
      default: "juju"
      type: string
      description: |
        Used by the nrpe subordinate charms.
        A string that will be prepended to instance name to set the host name
        in nagios. So for instance the hostname would be something like:
            juju-myservice-0
        If you're running multiple environments with the same services in them
        this allows you to differentiate between them.
    nagios_servicegroups:
      default: ""
      type: string
      description: |
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup
    nagios_alert_if_juju_enabled:
      default: False
      type: boolean
      description: |
        This enables a Nagios alert that will warn if Juju commands are enabled when we expect them to be disabled.
    nagios_check_pacemaker:
      default: False
      type: boolean
      description: |
        Run Nagios checks to determine the state of Corosync/Pacemaker.
